# Generated by Django 4.0.5 on 2022-07-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='non.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
